"""empty message

Revision ID: 6b502d8ed703
Revises: 2ee20a1f9947
Create Date: 2025-11-27 21:15:53.624398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b502d8ed703'
down_revision = '2ee20a1f9947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('crew', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('height', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('mass', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('homeworld_url', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diameter', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('gravity', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('edited_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('gravity')
        batch_op.drop_column('diameter')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('edited_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('homeworld_url')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('mass')
        batch_op.drop_column('height')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('birth_year')

    op.drop_table('vehicle')
    # ### end Alembic commands ###
